/**
 * Sahakari Demo & Fallback Datasets
 * Provides reliable fallback records for categories, verified cooperative workers,
 * live negotiations, and telemetry bookings when the external backend is offline.
 */

export const mockCategories = [
  {
    id: 'plumbing',
    name: 'Plumbing & Pipe Repairs',
    description: 'Emergency leak sealing, pipe fitting, faucet replacement, and drainage maintenance.',
    icon: 'plumbing',
    popular: true,
    activeWorkersCount: 18,
    startingPrice: 349,
  },
  {
    id: 'electrical',
    name: 'Electrical & Wiring',
    description: 'Short circuit diagnostics, MCB installations, appliance cabling, and fan repairs.',
    icon: 'electric_bolt',
    popular: true,
    activeWorkersCount: 24,
    startingPrice: 299,
  },
  {
    id: 'hvac',
    name: 'AC & Appliance Service',
    description: 'Split AC gas refills, cooling diagnostics, washing machine, and refrigerator fixes.',
    icon: 'mode_fan',
    popular: true,
    activeWorkersCount: 15,
    startingPrice: 499,
  },
  {
    id: 'carpentry',
    name: 'Carpentry & Woodwork',
    description: 'Door hinge fixes, modular furniture assembly, lock replacement, and custom polishing.',
    icon: 'carpenter',
    popular: false,
    activeWorkersCount: 12,
    startingPrice: 399,
  },
  {
    id: 'cleaning',
    name: 'Deep Home Cleaning',
    description: 'Kitchen degreasing, sofa shampooing, bathroom sterilization, and full home sanitize.',
    icon: 'cleaning_services',
    popular: false,
    activeWorkersCount: 31,
    startingPrice: 599,
  },
  {
    id: 'painting',
    name: 'House Painting & Polish',
    description: 'Interior wall touchups, waterproof coating, damp treatment, and designer finishes.',
    icon: 'format_paint',
    popular: false,
    activeWorkersCount: 9,
    startingPrice: 899,
  },
];

export const mockWorkers = [
  {
    id: 'worker-1',
    name: 'Suresh Patel',
    title: 'Senior Master Plumber & HVAC Pro',
    category: 'plumbing',
    categoryName: 'Plumbing',
    rating: 4.9,
    reviewsCount: 148,
    avatar: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
    distance: '1.2 km away',
    startingPrice: 450,
    hourlyRate: 450,
    experience: '12 years exp',
    phone: '+91 98765 43210',
    verified: true,
    coopMember: true,
    completedJobs: 312,
    skills: ['Copper Pipe Repair', 'Emergency Shutoff', 'Leak Detection', 'Drain Clearing', 'Sanitary Fitting'],
    lat: 28.5535,
    lng: 77.2062,
    badge: 'Coop Partner • Tier 1',
  },
  {
    id: 'worker-2',
    name: 'Amitabh Sen',
    title: 'Certified Master Electrician',
    category: 'electrical',
    categoryName: 'Electrical',
    rating: 4.8,
    reviewsCount: 96,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    distance: '2.1 km away',
    startingPrice: 350,
    hourlyRate: 350,
    experience: '9 years exp',
    phone: '+91 98234 56789',
    verified: true,
    coopMember: true,
    completedJobs: 215,
    skills: ['MCB Tripping Isolation', 'Inverter Wiring', 'Insulation Testing', 'Smart Switch Setup'],
    lat: 28.5612,
    lng: 77.2014,
    badge: 'Coop Partner • Tier 1',
  },
  {
    id: 'worker-3',
    name: 'Priya Nair',
    title: 'HVAC Specialist & Appliance Lead',
    category: 'hvac',
    categoryName: 'AC & Appliances',
    rating: 4.9,
    reviewsCount: 112,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    distance: '2.8 km away',
    startingPrice: 550,
    hourlyRate: 550,
    experience: '8 years exp',
    phone: '+91 98345 67890',
    verified: true,
    coopMember: true,
    completedJobs: 189,
    skills: ['R32 Refrigerant Gas Refill', 'Dual Capacitor Test', 'Inverter PCB Diagnostic', 'Deep Coil Jet Wash'],
    lat: 28.5678,
    lng: 77.1965,
    badge: 'Certified Specialist',
  },
  {
    id: 'worker-4',
    name: 'Rajesh Sharma',
    title: 'Master Carpenter & Joiner',
    category: 'carpentry',
    categoryName: 'Carpentry',
    rating: 4.7,
    reviewsCount: 84,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    distance: '3.4 km away',
    startingPrice: 400,
    hourlyRate: 400,
    experience: '14 years exp',
    phone: '+91 98456 78901',
    verified: true,
    coopMember: true,
    completedJobs: 278,
    skills: ['Lock Mortise Repair', 'Hydraulic Hinge Fitting', 'Modular Furniture Assembly', 'Wood Polish'],
    lat: 28.5710,
    lng: 77.1920,
    badge: 'Coop Partner',
  },
];

export const initialNegotiationChats = {
  'worker-1': [
    {
      id: 'msg-1',
      sender: 'CUSTOMER',
      senderName: 'You',
      time: '10:42 AM',
      text: 'Hello Suresh, I have a sudden copper pipe leak under the kitchen sink. Water valve is turned off. What would you charge?',
      amount: 400,
      type: 'OFFER',
    },
    {
      id: 'msg-2',
      sender: 'WORKER',
      senderName: 'Suresh Patel',
      time: '10:45 AM',
      text: 'Hello! I can reach your location in 20 minutes with high-grade compression fittings and pressure testing equipment. Standard emergency rate is ₹500 including 90-day coop warranty.',
      amount: 500,
      type: 'COUNTER',
    },
    {
      id: 'msg-3',
      sender: 'CUSTOMER',
      senderName: 'You',
      time: '10:48 AM',
      text: 'Could we settle on ₹450? If so, I will confirm the booking immediately.',
      amount: 450,
      type: 'COUNTER',
    },
    {
      id: 'msg-4',
      sender: 'WORKER',
      senderName: 'Suresh Patel',
      time: '10:50 AM',
      text: 'Deal! ₹450 works for me. Please confirm the booking and I will head over right away with my toolset.',
      amount: 450,
      type: 'COUNTER',
    },
  ],
};

export const defaultBooking = {
  id: 'BK-7892',
  serviceName: 'Emergency Pipe Repair & Joint Fitting',
  workerName: 'Suresh Patel',
  workerPhone: '+91 98765 43210',
  workerAvatar: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
  workerRating: 4.9,
  workerReviewsCount: 148,
  workerId: 'worker-1',
  customerName: 'Customer',
  customerAddress: '123 Safdarjung Enclave, New Delhi',
  customerPhone: '+91 99999 88888',
  status: 'IN_TRANSIT',
  statusLabel: 'Worker on the way',
  agreedPrice: 450,
  platformFee: 15,
  totalAmount: 465,
  paymentStatus: 'PAID',
  paymentMethod: 'UPI / Razorpay Escrow',
  createdAt: new Date().toISOString(),
  scheduledTime: 'Today, Immediate (Within 30 mins)',
  etaMinutes: 12,
  distanceRemainingKm: 1.2,
};

